Vagrant.configure("2") do |config|
(1..10).each do |i|
    config.vm.define "vgnode#{i}" do |node|
	node.vm.box = "generic/debian10"
	node.vm.hostname = "deb10-vgnode#{i}"
	node.vm.network :public_network,
			:dev => "eth0",
			:mode => "bridge",
			:type => "bridge"
	node.vm.provider "libvirt" do |kvm|
	    kvm.default_prefix="deb10_"
	    kvm.memory=512
	    kvm.cpus=1
	end
	node.vm.provision "shell", inline: "hostnamectl set-hostname deb10-vgnode#{i}"
	node.vm.synced_folder './', '/deb10'
	node.vm.provision "shell", inline: <<-SHELL
	    mkdir /root/.ssh
	    cat /deb10/id_rsa.pub >> /root/.ssh/authorized_keys
#	    cat /deb10/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
	SHELL
    end
end
end
