Vagrant.configure("2") do |config|
(1..20).each do |i|
    config.vm.define "vgnode#{i}" do |node|
	node.vm.box = "generic/debian10"
	node.vm.hostname = "deb10-vgnode#{i}"
	node.vm.network :public_network, :dev => "kvmbr-debswarm", :mode => "bridge", :type => "bridge"
	node.vm.provider "libvirt" do |kvm|
	    kvm.memory=1024
	    kvm.cpus=1
	end
	node.vm.provision "shell", inline: <<-SHELL
	    hostnamectl set-hostname deb10-vgnode#{i}
	    mkdir /root/.ssh
	    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLugqBFpAq2oK08bxJU7AS7cGPleVq5gjird8qp/bOfAiWup3NXz6bUU+wDDnJHGEs4lnF2FMKKCx5WHVWdKq4O6rXtrDwAF9z/x2uJ4w6+sr4+pdqEHSwqESArMp0QpAeV2lWoPEUJwiZ2j1lcob4he0iBcY3wuYJM4ryY0834mCaPwDmy1Dqoj3ST1z6oDFX+4RpNuM5Rq76doFg8W/9JWtBVytwpL0O8DxvT5zeegO8RjvsT9yHO8GYUsxzcaOIJaJYXyqfySwvgOPy2pahqJZUKYgD8Cs+u9qtuJSdi8rXHkpNdd2RpW50X+xrBtyFEllTPFyoqCi0T+rGssbJ root@hyperion"   >> /home/vagrant/.ssh/authorized_keys
	    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLugqBFpAq2oK08bxJU7AS7cGPleVq5gjird8qp/bOfAiWup3NXz6bUU+wDDnJHGEs4lnF2FMKKCx5WHVWdKq4O6rXtrDwAF9z/x2uJ4w6+sr4+pdqEHSwqESArMp0QpAeV2lWoPEUJwiZ2j1lcob4he0iBcY3wuYJM4ryY0834mCaPwDmy1Dqoj3ST1z6oDFX+4RpNuM5Rq76doFg8W/9JWtBVytwpL0O8DxvT5zeegO8RjvsT9yHO8GYUsxzcaOIJaJYXyqfySwvgOPy2pahqJZUKYgD8Cs+u9qtuJSdi8rXHkpNdd2RpW50X+xrBtyFEllTPFyoqCi0T+rGssbJ root@hyperion"   >> /root/.ssh/authorized_keys
	SHELL
    end
end
end
